version: '3.3'
services:
    httpd:
        container_name: wed-server
        restart: unless-stopped
        ports:
            - '32102:80'
        volumes:
            - '/root/coder/config/workspace/site-casamento:/usr/local/apache2/htdocs/'
        image: 'httpd:2.4'
